site_name: CSC Map of the World
site_url: https://data-to-insight.github.io/csc-map-of-the-world/

theme:
  name: material
  palette:
    scheme: default

nav:
  - Home: index.md
  - Explore: explore.md

  - Network, full screen: network_fullscreen.md # TESTING

  - CSC Network: network.md
  - CSC Network Relations: sccm_relation_types.md
  - CSC Search: search.md
  - CSC Search Strategy: search_pipeline.md
  - CSC Search Sources: sources.md

  - Submit Entry: form/index.html


extra_javascript:
  - https://unpkg.com/cytoscape@3.24.0/dist/cytoscape.min.js
  - https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js
  # - js/render_graph.js
  - js/search_tool.js  


extra_css:
  - css/styles.css
  - https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css

site_dir: site

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
